# Generated by Django 3.2.1 on 2021-05-07 13:29

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_podcast_participants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='participants',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=list, size=None, validators=[django.core.validators.MaxLengthValidator(10)]),
        ),
    ]
